version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /frontend/guarantee_application
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
