name: flutter_camera_app
description: A new Flutter Camera application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/ic_flutter_devs_logo.png
    - assets/images/ic_powered_by.png
    - assets/images/ic_shutter_1.png
    - assets/images/ic_switch_camera_3.png
    - assets/images/ic_no_image.png
